version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
    - NODE_ENV=production
    - PORT=8000
    - DATABASE_URL=postgres://postgres:postgres@postgres:5432/d1cjs992d8sbtq?ssl=true

  postgres:
    build: ./database
    environment:
      POSTGRES_PASSWORD: postgres