name: Build & Deploy

on:
  push:
    branches:
    - master
    - release/*
  pull_request:

jobs:
  build:
    name: Build & test the application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Installing, building and testing the application
        working-directory: ./
        run: |
          npm install
          npm run build --if-present
          npm test

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Deploy the application to Heroku
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "oamk-pathfinder"
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master